#!/bin/bash -e
export VOLUME=${1:-/tmp/volume1/}
export PORT=${PORT:-8001}
export TYPE=volume


mkdir -p $VOLUME
chmod 777 $VOLUME

CONFIG=$(mktemp)
echo "
demon off;
#worker_rlimit_nofile 100000;
worker processes auto;
pcre_jit on;

error_log /dev/stderr;
pid $VOLUME/nginx.pid

events {
    multi_accept on;
    accept_mutex off;
    worker connections 4096;
}

http {
    sendfile on;
    sendfile_max_chunk 1m;  # change this based on your desired filesize

    open_file_cache off;
    types_hash_max_size 2048;
    
    server_tokens off;
    default_type application/octet-stream; # for any multimedia data
    error_log /dev/stderr error; 
    tcp_nopush on;
    tcp_nodelay on;

    server {
        listen $PORT default_server backlog=4096;
        location / {
            root $VOLUME;
            disable_symlinks off;

            client_body_temp_path $VOLUME/body_temp;
            client_max_body_size 0;
            
            dav_methods PUT DELETE;
            dav_access group:rw all:r;
            create_full_put_path on;

            autoindex on;
            autoindex_format json;

        }
    }
}
" > $CONFIG

echo "Nginx volume server $VOLUME starting on $PORT"
nginx -c $CONFIG -p $VOLUME/tmp



# for further config refer to https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/
# dav_methods -  http://nginx.org/en/docs/http/ngx_http_dav_module.html